### PR TITLE
Show alert if Layer or Parse keys aren't set

### LINKED ISSUE #27: Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'
```
2016-03-03 16:49:31.385 Layer-Parse-iOS-Example[39344:2109829] LayerKit client v0.19.2 loaded
2016-03-03 16:49:31.482 Layer-Parse-iOS-Example[39344:2109829] *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3512.30.14/UIApplication.m:3315
2016-03-03 16:49:31.484 Layer-Parse-iOS-Example[39344:2109829] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000110b23e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000011059cdeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000110b23cca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00000001101e94de -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   UIKit                               0x000000010ec08218 -[UIApplication _runWithMainScene:transitionContext:completion:] + 3122
	5   UIKit                               0x000000010ec04e7b -[UIApplication workspaceDidEndTransaction:] + 188
	6   FrontBoardServices                  0x000000011328f754 -[FBSSerialQueue _performNext] + 192
	7   FrontBoardServices                  0x000000011328fac2 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	8   CoreFoundation                      0x0000000110a4fa31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x0000000110a4595c __CFRunLoopDoSources0 + 556
	10  CoreFoundation                      0x0000000110a44e13 __CFRunLoopRun + 867
	11  CoreFoundation                      0x0000000110a44828 CFRunLoopRunSpecific + 488
	12  UIKit                               0x000000010ec047cd -[UIApplication _run] + 402
	13  UIKit                               0x000000010ec09610 UIApplicationMain + 171
	14  Layer-Parse-iOS-Example             0x000000010da0bf0f main + 111
	15  libdyld.dylib                       0x0000000110fcf92d start + 1
	16  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

### PR DESCRIPTION
**Pull request by feifanzhou**
Close #27 
Close #28

### CODE REVIEW

File: Code/AppDelegate.m [hunk 1]
```diff
@@ -26,15 +26,12 @@
 @implementation AppDelegate
 
 #pragma mark TODO: Before first launch, update LayerAppIDString, ParseAppIDString or ParseClientKeyString values
-#warning "TODO:If LayerAppIDString, ParseAppIDString or ParseClientKeyString are nil, this app will crash"
 static NSString *const LayerAppIDString = nil;
```
Comment (maju6406) [inline Code/AppDelegate.m]: Let's keep the warning in there.

Comment (feifanzhou) [inline Code/AppDelegate.m]: Well it won't crash anymore … maybe say "If x, y, or z are nil, this app won't work correctly"?

Comment (maju6406) [inline Code/AppDelegate.m]: Agreed. change the warning to say that the project won't work without it.
